server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FeatureFlagsDB
    username: SA
    password: msSQLp@55
    driver-class-name:  com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialization-mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        default_schema: feature_flags
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  flyway:
    enabled: true
    schemas: feature_flags
    baseline-on-migrate: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace